---
# This is for arm
- name: ARM | Get latest verion from github
  github_release:
    user: "{{ gh_user }}"
    repo: "{{ gh_repo }}"
    action: latest_release
  when: "bat_version is empty"
  register: bat_version

- name: ARM | Unpack tar
  unarchive:
    src: "{{ arm_url }}"
    dest: "{{ arm_tmp }}"
    remote_source: yes

- name: ARM | Copy bin to /usr/local/bin/bat
  become: true
  copy:
    src: "{{ arm_tmp }}/bat"
    dest: "{{ arm_target }}"
    mode: "{{ arm_filemode }}"

- name: ARM | Remove folder
  file:
    path: "{{ arm_tmp }}"
    state: abesent
