---
# This is for arm
- name: ARM | Unpack tar
  unarchive:
    src: "{{ arm_url }}"
    dest: "{{ arm_tmp }}"
    remote_source: yes

- name: ARM | Copy bin to /usr/local/bin/bat
  become: true
  copy:
    src: "{{ arm_tmp }}/bat"
    dest: "{{ arm_target }}"
    mode: "{{ arm_filemode }}"

- name: ARM | Remove folder
  file:
    path: "{{ arm_tmp }}"
    state: abesent
