---
# This is for Debian/Ubuntu
- name: DEBIAN | Download deb-file
  get_url:
    url: "{{ debian_url }}"
    dest: "{{ debian_tmp }}/bat.deb"

- name: DEBIAN | Install with dpkg
  become: true
  shell:
    command: "dpkg --install --yes {{ debian_tmp }}/bat.deb"

- name: DEBIAN | Remove deb-file
  file:
    path: "{{ debian_tmp }}/bat.deb"
    state: absent
