---
- name: GENERAL | Get current version of docker-compose
  shell: >
      warn=False
      curl --silent https://api.github.com/repos/{{ gh_user }}/{{ gh_repo }}/releases/latest |
      grep '"tag_name":' |
      grep -Po '[0-9.]+'
  register: command_result
  failed_when: >
    command_result.rc != 0 or
    not command_result.stdout|regex_search('\w+\.\w+\.\w+')
  when: bat_version is empty

- name: GENERAL | Set latest version of docker-compose
  set_fact:
    bat_version: "{{ command_result.stdout }}"
  when: bat_version is empty

- name: GENERAL | Set URLs to download bins
  set_fact:
    debian_url: "{{ gh_repo_url }}/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb"
    arm_url: "{{ gh_repo_url }}/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-arm-unknown-linux-gnueabihf.tar.gz"

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: arch.yml
  when: ansible_distribution == 'ArchLinux'

- import_tasks: void.yml
  when: ansible_distribution == 'VoidLinux'

- import_tasks: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- import_tasks: macos.yml
  when: ansible_distribution == 'MacOS'

- import_tasks: arm.yml
  when: ansible_architecture == 'arm'
